language: php

php:
  # - '5.6'
  - '7.0.8'
  #- '7.1'

sudo: false

before_script:
  - php -r "file_exists('.env') || copy('.env.example', '.env');"
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit --exclude-group=integrations

notifications:
  email:
    recipients:
      - hello@handesk.io
    on_success: never
    on_failure: always